ci:
  autoupdate_schedule: quarterly

default_stages: [commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: https://github.com/janosh/format-ipy-cells
    rev: v0.1.10
    hooks:
      - id: format-ipy-cells

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: ^assets/.+\.(svg|html)$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        exclude_types: [csv, svg, html, yaml, jupyter]
        args: [--ignore-words-list, "hist,mape"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, --keep-output]

  - repo: local
    hooks:
      - id: no-missing-readme-images
        name: No missing readme images
        entry: python -c 'from tests.test_readme import test_no_missing_images; test_no_missing_images()'
        language: system
        files: readme.md
