ci:
  autoupdate_schedule: quarterly
  skip: [pyright]

default_stages: [commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, jupyter]
      - id: ruff-format
        types_or: [python, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]

  - repo: https://github.com/janosh/format-ipy-cells
    rev: v0.1.11
    hooks:
      - id: format-ipy-cells

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: ^assets/.+\.(svg|html)$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        exclude_types: [csv, svg, html, yaml, jupyter]
        args: [--ignore-words-list, "hist,mape,te,nd,fpr", --check-filenames]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, --keep-output]

  - repo: local
    hooks:
      - id: no-missing-readme-images
        name: No missing readme images
        entry: python -c 'from tests.test_readme import test_no_missing_images; test_no_missing_images()'
        language: system
        files: readme.md

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte
        exclude: ^(site/src/figs/.+\.svelte|data/wbm/20.+\..+|site/src/(routes|figs).+\.(yaml|json)|changelog.md)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.1
    hooks:
      - id: eslint
        stages: [manual] # TODO: skip eslint for now
        types: [file]
        args: [--fix, --config, site/eslint.config.js]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - eslint-plugin-svelte
          - svelte
          - typescript
          - typescript-eslint

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.378
    hooks:
      - id: pyright
