[tool.ruff]
target-version = "py38"
select = [
  "F",   # pyflakes
  "E",   # pycodestyle
  "I",   # isort
  "W",
  "YTT", # flake8-2020
  "B",   # flake8-bugbear
  "Q",   # flake8-quotes
  "PLE", # pylint
  "PLW",
  "TID", # tidy imports
  "C",
  "RET",
  "S",
  "D",
]
ignore = [
  "B019",
  # Within an except clause, raise exceptions with ...
  "B904",
  # Magic number
  "PLR2004",
  "S101",    # Use of `assert` detected
  "D100",    # Missing docstring in public module
  "B905",
  "C408",
  "S101",
  "S113",
  "C901",
  "RET504",
  "D100",
  "D104",
  "D205",    # 1 blank line required between summary line and description
]
pydocstyle.convention = "google"
isort.lines-after-imports = 2

[tool.ruff.per-file-ignores]
# D103 Missing docstring in public function
# E402 Module level import not at top of file
"tests/*.py" = ["D103"]
"examples/*.py" = ["E402"]
