name: GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: janosh/workflows/.github/workflows/nodejs-gh-pages.yml@main
    with:
      python-version: "3.11"
      working-directory: site
      pre-build: |
        pip install '..[gh-pages]'
        npm run make-html-examples
        python ../assets/make_api_docs.py
