name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: janosh/workflows/.github/workflows/pytest-release.yml@main
    with:
      os: ${{ matrix.os }}
      pre-test: export MPLBACKEND=Agg # https://github.com/orgs/community/discussions/26434
